# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12P7vx_rqbgmmCJiyB6XN_5BcoQc8b-k6
"""
import torch
import torch.optim as optim
from torch.utils.data import DataLoader
from tqdm import tqdm
import sys
sys.path.insert(2, './config')
sys.path.insert(3, './processing')
sys.path.insert(4, './models')
import data_management
import BERT_tokenizer
import finetune
import models
import camelot
import pandas as pd
from PyPDF2 import PdfReader
import re

tables = camelot.read_pdf('./datasets/BP-0002.pdf', pages='1,2,3,4,5,6,7,8,9,10,11,12,13,14',line_scale=40)

reader = PdfReader("./datasets/BP-0002.pdf")
doc_length = len(reader.pages)
page = reader.pages[0]
t = page.extract_text()
text = str(t)

text = t.replace("\n", " ").replace(",","")
print(text)

paragraphOne = re.search("_    (.*?)  1", text, re.S)
paragraphOne = paragraphOne.group(1)
processedParagraphOne = re.sub(r'[^\w]', ' ', paragraphOne)
print(paragraphOne)

BABERT = torch.load('./models/BABERT.pth')
models.BA_Model(BABERT, processedParagraphOne)

